### ISSUE TITLE
Collect (scrape/request) the consolidated datasources

### ISSUE THREAD

**Issue by Deepthi-Chand** [DataKind-BLR/OpenCity-Sprint-2018#5] opened 2018-06-12 22:16 UTC

**Comment by atishjainms** [comment] 2018-06-13 09:15
Will check out the Open street maps API

**Comment by raghuramdr** [comment] 2018-08-19 10:01
Scraping is done. Consolidation has started

**Comment by raghuramdr** [comment] 2018-08-19 10:02
Duplicate of similar issue. Closing this

**Closed by raghuramdr** 2018-08-19 10:02 UTC
